id: D7A122AA3
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-04-18T11:13:34+00:00'
last_modified: '2022-05-30T06:51:44.800626+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/a7eec5e12ddce18d0ed1dbb732a42cf48f94dd09/openpecha/formatters/hfml.py
source_metadata:
  base:
    73ff:
      image_group_id: I1PD95887
      title: ''
      total_pages: 1712
      order: 42
      base_file: 73ff.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
