id: P36F99D39
initial_creation_type: ocr
source_metadata:
  volumes:
    1d18f4af03bd49ff8673c3abc930e49b:
      base_file: v042.txt
      image_group_id: I1PD95887
      title: ''
      total_pages: 1712
      volume_number: 42
